version: "3.8"

services:
  customer-service:
    container_name: customer-service
    image: customer-service
    build:
      context: ./customer-service/
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=r2dbc:postgresql://localhost:5432/db_customer
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123123
      - PORT=8080
      - TRANSACTION_SERVICE_URL=http://transactions-service:8082
    ports:
      - "8080:8080"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 700M
      restart_policy:
        condition: on-failure
    depends_on:
      - db_customer
    networks:
      - reactive-network
     
  transactions-service:
    container_name: transactions-service
    image: transactions-service
    build:
      context: ./transactions-service/
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=r2dbc:postgresql://localhost:5432/db_transactions
      - DATABASE_URL=postgres
      - DATABASE_PASSWORD=123123
      - PORT=8082
      - CUSTOMER_SERVICE_URL=http://customer-service:8080
    ports:
      - "8082:8082"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 700M
      restart_policy:
        condition: on-failure
    depends_on:
      - db_transactions
    networks:
      - reactive-network
      
  db_customer:
    container_name: ddb_customer
    image: postgres:latest
    environment:
      - POSTGRES_DB=db_customer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - TZ=America/Guayaquil
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - reactive-network
      
  db_transactions:
    container_name: db_transactions
    image: postgres:latest
    environment:
      - POSTGRES_DB=db_transnation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - TZ=America/Guayaquil
    ports:
      - "5433:5432"
    restart: on-failure
    networks:
      - reactive-network

networks:
  reactive-network:
    name: reactive-network
    driver: bridge
